# Generated by Django 4.2.11 on 2024-03-09 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("date_start", models.DateField(default=datetime.date.today)),
                ("date_end", models.DateField(default=datetime.date.today)),
                ("color", models.CharField(max_length=7)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
